name: Rust Cross-Platform Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build Release
      run: cargo build --release --target ${{ matrix.target }}

    - name: Prepare Release Assets
      run: |
        mkdir -p ./artifacts
        cp target/${{ matrix.target }}/release/${{ github.event.repository.name }} ./artifacts/${{ github.event.repository.name }}-${{ matrix.target }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifacts/${{ github.event.repository.name }}-${{ matrix.target }}
